### ISSUE TITLE
Focus does not seem to be detected

### ISSUE THREAD

**Issue by shlomiv** [xinario/defocus_segmentation#1]
Hi,
I was trying to get this to work on a set of pictures. But it seemed to not identify focused parts, the segmentation looks like noise.. 

Generated the frames with
``` 
> find images -name "*.jpg" -exec python lbpSharpness.py --input {} \;
```
Then turned the images into a gif using:
```
> ffmpeg \
  -framerate 60 \
  -pattern_type glob \
  -i '*.jpg' \
  -r 15 \
  -vf scale=640:-1 \
  out.gif
```
![out](https://user-images.githubusercontent.com/379063/80835922-92b01000-8ba8-11ea-8621-0cc4d5c49bdf.gif)

I tried to mess around with `s` and `threshold` parameters, but with no luck..

Any pointers?

**Comment by xinario** [comment]
Do you mind to share the original images with me so that I can take a look? My gutting feeling is that the noise level is too high.

**Comment by shlomiv** [comment]
Hi @xinario, thank you for responding, and sorry for the delay!
Sure, I added two of the images with different focused sections, https://drive.google.com/drive/folders/1BSZPr2_cNN-_Z8ch8pmESU6lGbZcSTKC?usp=sharing

These are JPEG projections, but the originals are RAW files from a DSLR, so different pre-processing can be applied. 

Please let me know when you downloaded these files so I can remove them from my drive account, nearing my limits :)

Thank you for your time!

**Comment by xinario** [comment]
I had a very quick try on your images and it definitely is because of the noise. 
So I downsampled the image by 8
img = img[::8,::8, :]
and then applied a simple nonlocal mean filter
img_gray = cv2.fastNlMeansDenoising(img_gray, h=3)

here is the results I get which look reasonable to me (of course you can tune these parameters a bit to maybe get slightly better result).
![DSC_0081_small_out](https://user-images.githubusercontent.com/4955152/81345988-b971b900-9076-11ea-9b7c-18838370c4e8.jpg)
![DSC_0095_small_out](https://user-images.githubusercontent.com/4955152/81346013-c4c4e480-9076-11ea-83b1-3a9bb77dc111.jpg)

**Comment by shlomiv** [comment]
Definitely looks much better. Thank you!
